name: eatme
description: Preventing food waste.

version: 1.2.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"


flutter:
  uses-material-design: true
  assets:
    - assets/icon_big.png

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"